### ISSUE TITLE
Error  'restart php-fpm7.0' 

### ISSUE THREAD

**Issue by NPreston** [kirsenn/vagrant#1]
Incorrect command php-fpm:
`==> default: ERROR! The requested handler 'restart php-fpm7.0' was not found in any of the known handlers
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
`

TODO:
Rename `name: restart php-fpm` to `name: restart php-fpm7.0` in _ansible/roles/php/handlers/main.yml_

**Comment by kirsenn** [comment]
Thank you
